name: hello_world
author: Dart Team <web@dartlang.org>
description: Hello World example.
environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'
dependencies:
  angular: ^5.0.0-alpha+4
dev_dependencies:
  build_runner: ^0.7.8
  build_web_compilers: 0.2.1
